In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[1:3] #Slice based on rows

array([[4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[2][1]

8

In [8]:
arr.sum()

45

In [9]:
arr.min()

1

In [10]:
arr.max()

9

In [11]:
arr.max(axis=0)

array([7, 8, 9])

In [12]:
arr.max(axis=1)

array([3, 6, 9])

In [13]:
new_arr = np.array([10]) #No, of elements should be 1 or match the no. of element in each row of arr 2

arr *new_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
new_arr = np.array([10,5,2]) #No, of elements should be 1 or match the no. of element in each row of arr 2

arr *new_arr

array([[10, 10,  6],
       [40, 25, 12],
       [70, 40, 18]])

In [17]:
rng = np.random.default_rng() #Random Number generator

rng.random(5)

array([0.75512457, 0.91483582, 0.76436965, 0.0375674 , 0.36319776])

In [20]:
rng.random((2,5))

array([[0.78439656, 0.82501444, 0.51465419, 0.44144498, 0.51423197],
       [0.02398564, 0.82654509, 0.76727056, 0.51058604, 0.04501178]])