In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [3]:
arr1+arr2

array([5, 7, 9])

In [4]:
arr1-arr2

array([-3, -3, -3])

In [5]:
arr1*arr2

array([ 4, 10, 18])

In [6]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [7]:
arr1.sum()

6

In [8]:
arr = np.array([[1,2,3],
               [11,12,13]])
arr

array([[ 1,  2,  3],
       [11, 12, 13]])

In [9]:
arr.sum()

42

In [10]:
arr.mean()

7.0

In [11]:
arr.max()

13

In [12]:
arr.min()

1

In [13]:
arr.sum(axis=0)

array([12, 14, 16])

In [14]:
arr.sum(axis=1)

array([ 6, 36])