In [1]:
import numpy as np

In [3]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
arr2 = arr[3:5]

arr2

array([4, 5])

In [6]:
arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[7,8,9],
                [10,11,12]])

arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr3 = np.vstack((arr1,arr2))

arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arr4 = np.hstack((arr1,arr2))

arr4

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [13]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
original = np.arange(10)

original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
copy = original[3:7]

copy

array([3, 4, 5, 6])

In [16]:
copy[0]=999
copy

array([999,   4,   5,   6])

In [17]:
original

array([  0,   1,   2, 999,   4,   5,   6,   7,   8,   9])

In [18]:
original = np.arange(10)

original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
copy = original[3:7].copy()

copy

array([3, 4, 5, 6])

In [21]:
copy[0]= 999

copy

array([999,   4,   5,   6])

In [22]:
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])