In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [3]:
arr = np.array([1,2,3],dtype='str')

arr

array(['1', '2', '3'], dtype='<U1')

In [4]:
arr = np.array([1,2,3],dtype='int8')

arr

array([1, 2, 3], dtype=int8)

In [5]:
zeros = np.zeros(5)

zeros

array([0., 0., 0., 0., 0.])

In [6]:
ones = np.ones(5)

ones

array([1., 1., 1., 1., 1.])

In [7]:
arr = np.empty(5) #faster compare to zeros and ones as it take the random value available in mem

arr

array([1., 1., 1., 1., 1.])

In [8]:
arr = np.arange(5)

arr

array([0, 1, 2, 3, 4])

In [9]:
arr = np.arange(0,5)

arr

array([0, 1, 2, 3, 4])

In [10]:
arr = np.arange(0,10,2)

arr

array([0, 2, 4, 6, 8])

In [11]:
arr = np.linspace(0,10,num=5) #Similar to arange, but create array with num number of elements with liniar split

arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])