In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

rng

Generator(PCG64) at 0x109037920

In [3]:
rng.integers(low=1, high=3,size=(2,3)) #High value will be excluded

array([[1, 1, 1],
       [2, 1, 1]])

In [4]:
rng.integers(low=1, high=3,size=(2,3), endpoint=True) #Includes High Value

array([[3, 1, 2],
       [1, 2, 2]])

In [7]:
rng.random(size=(2,3,6)) # get random float values between 0 and 1

array([[[0.6268186 , 0.78558409, 0.90429487, 0.15787746, 0.72177799,
         0.58479129],
        [0.524618  , 0.6050084 , 0.67451732, 0.21744836, 0.96634597,
         0.93860168],
        [0.80559852, 0.73204568, 0.39114312, 0.67417311, 0.65494662,
         0.15625212]],

       [[0.17731096, 0.12387119, 0.85531187, 0.24566009, 0.29081173,
         0.05042214],
        [0.00920707, 0.47933516, 0.3241051 , 0.08875689, 0.46210904,
         0.85153256],
        [0.77588448, 0.02082927, 0.28077425, 0.50244127, 0.70974949,
         0.25269018]]])