In [1]:
import numpy as np

In [2]:
arr = np.arange(6)

arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [4]:
np.flip(arr)

array([5, 4, 3, 2, 1, 0])

In [5]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [8]:
np.flip(arr) #reverse both Column and Rows

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [9]:
np.flip(arr,axis=0) #Reverse only Rows

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [10]:
np.flip(arr,axis=1) #Reverse only Columns

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [11]:
np.flip(arr[0])

array([3, 2, 1])

In [12]:
np.flip(arr[:,2])

array([9, 6, 3])