In [1]:
import numpy as np

In [2]:
np.sort([5,1,6,3,8,2,5,4,9,0])

array([0, 1, 2, 3, 4, 5, 5, 6, 8, 9])

In [3]:
arr_a = np.array([1,2,3])

arr_b = np.array([4,5,6])

In [6]:
np.concatenate((arr_a,arr_b))

array([1, 2, 3, 4, 5, 6])

In [7]:
arr_a = np.array([[1,2,3],
                [4,5,6]])

arr_b = np.array([[7,8,9],
                 [10,11,12]])

In [9]:
np.concatenate((arr_a,arr_b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])