In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.shape

(6,)

In [4]:
arr2 = arr[np.newaxis,:] #Add Row

arr2

array([[1, 2, 3, 4, 5, 6]])

In [5]:
arr2.shape

(1, 6)

In [6]:
arr3 = arr[:,np.newaxis]

arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
arr3.shape

(6, 1)

In [8]:
np.expand_dims(arr,axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [9]:
np.expand_dims(arr,axis=0).shape

(1, 6)

In [10]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
np.expand_dims(arr,axis=0).shape

(1, 6)