In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1]

1

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([5, 6, 7, 8, 9])

In [7]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
arr[arr>5]

array([6, 7, 8, 9])

In [9]:
arr_mask = arr%2 == 0
arr[arr_mask]

array([0, 2, 4, 6, 8])

In [10]:
arr_mask = (arr%2 == 0) & (arr !=0)

arr[arr_mask]

array([2, 4, 6, 8])

In [13]:
arr.nonzero() #no arguments is accessing function through arr object

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr.shape

(3, 4)

In [16]:
arr_mask = np.nonzero(arr > 5)

arr_mask # Return tuple of 2 array. elements in 1st array tells the row index and 2nd will tell the column index

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [17]:
arr[arr_mask]

array([ 6,  7,  8,  9, 10, 11, 12])