In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [3]:
arr * .5 #Broadcast .5 to all elements in array

array([0.5, 1. , 1.5])

In [4]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5])

In [5]:
arr1 * arr2 # Wont work as size is not same both the arrays

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [6]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

In [7]:
arr1 * arr2 #Works

array([ 4, 10, 18])

In [8]:
arr1 = np.array([1,2,3])

arr2 = np.array([[4],
                [5],
                [6]])

In [9]:
arr1 * arr2

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])