In [1]:
import numpy as np

In [2]:
#.save -> Save single ND array as binary file. File ext: .npy
#.savez -> Save Multi ND array as binary file. File ext: .npz
#.savetxt -> Save as CSV or TXT file

In [3]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
np.save("sample_np.npy",arr)

In [5]:
np.load("sample_np.npy")

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
np.savetxt("sample.csv",arr)

In [7]:
np.loadtxt("sample.csv")

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])