In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,1,4,5,2,4,3,9,8,2])

arr

array([1, 2, 3, 1, 4, 5, 2, 4, 3, 9, 8, 2])

In [3]:
np.unique(arr) #Returns only the unique values from the array

array([1, 2, 3, 4, 5, 8, 9])

In [5]:
np.unique(arr,return_index=True) #Return unique values and the index of 1st occurance of the element

(array([1, 2, 3, 4, 5, 8, 9]), array([ 0,  1,  2,  4,  5, 10,  9]))

In [6]:
np.unique(arr,return_index=True,return_counts=True) # Return no. of counts

(array([1, 2, 3, 4, 5, 8, 9]),
 array([ 0,  1,  2,  4,  5, 10,  9]),
 array([2, 3, 2, 2, 1, 1, 1]))

In [7]:
arr1 = np.array([[1,1,2],
                [3,3,4],
                [1,1,2]])

arr1

array([[1, 1, 2],
       [3, 3, 4],
       [1, 1, 2]])

In [8]:
np.unique(arr1) # Return 1D array with all unique values

array([1, 2, 3, 4])

In [9]:
np.unique(arr1, axis=0)

array([[1, 1, 2],
       [3, 3, 4]])

In [10]:
np.unique(arr1, axis=1)

array([[1, 2],
       [3, 4],
       [1, 2]])