In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
arr.flatten() #Return 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr.ravel() #Similar to flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flattened = arr.flatten()
flattened[0]=10
flattened

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr #Faltten doen't change original array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
flattened = arr.ravel()
flattened[0]=10
flattened

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
arr #Ravel affects original array

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])